orb_slam3_mono:
  ros__parameters:
    vocabulary_path: /home/nvidia/drone/camera/orbslam3/ORB_SLAM3-master/Vocabulary/ORBvoc.txt
    settings_path: /home/nvidia/drone/camera/orbslam3/ORB_SLAM3-master/Examples/Monocular/TUM1.yaml
    image_topic: /camera/image_raw
    keyframe_trajectory_path: /home/nvidia/drone/camera/calibration/results/c330_KeyFrameTrajectory_TUM_Format.txt
    use_viewer: false
    queue_size: 10
